apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sportiverse-db-hpa
  namespace: sportiverse-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sportiverse-db-statefulset # Replace with actual DB deployment name
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Scale based on 50% CPU utilization
