apiVersion: v1
kind: PersistentVolume
metadata:
  name: sportiverse-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: '' # Ensure no StorageClass is used
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=999
    - gid=999
    - mfsymlinks
    - cache=strict
    - actimeo=30
    - noperm
    - nosharesock
  csi:
    driver: file.csi.azure.com
    volumeHandle: sportiverse-rg/sportiversestorageaccount/sportiverse-azure-file-share-static
    volumeAttributes:
      resourceGroup: sportiverse-rg
      shareName: sportiverse-azure-file-share-static
    nodeStageSecretRef:
      name: sportiverse-db-secret
      namespace: sportiverse-namespace
