apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sportiverse-pvc
  namespace: sportiverse-namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-premium
