apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sportiverse-db-statefulset
  namespace: sportiverse-namespace
  labels:
    app: sportiverse-db
spec:
  serviceName: 'sportiverse-statefulset-db-service' # Headless service for StatefulSet
  replicas: 1
  selector:
    matchLabels:
      app: sportiverse-db
  template:
    metadata:
      labels:
        app: sportiverse-db
    spec:
      serviceAccountName: sportiverse-db-sa
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: sportiverse-db-container
          image: mongo
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongodb-port
              containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: sportiverse-db-configmap
                  key: MONGODB_DB_NAME
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sportiverse-db-secret
                  key: MONGODB_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sportiverse-db-secret
                  key: MONGODB_PASSWORD
          resources:
            requests:
              memory: '1Gi'
              cpu: '500m'
            limits:
              memory: '2Gi'
              cpu: '1'
          volumeMounts:
            - name: mongodb-volume
              mountPath: /data/sportiverse-db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-volume # Name of the PVC to be created
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi # Size of the Persistent Volume for each pod
        storageClassName: 'managed-premium'
