apiVersion: v1
kind: Service
metadata:
  name: sportiverse-webapp-service
  namespace: sportiverse-namespace
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: sportiverse-webapp
