version: '3.8'

services:
  webapp:
    image: prasadhonrao/sportiverse-webapp:latest
    ports:
      - '${WEBAPP_PORT}:3000'
    environment:
      - REACT_APP_SPORTIVERSE_BASE_API_URI={REACT_APP_SPORTIVERSE_BASE_API_URI} + ':' + ${WEBAPP_PORT}
    depends_on:
      - webapi
  webapi:
    image: prasadhonrao/sportiverse-webapi:latest
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT=${PORT}
      - node_env=${node_env}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - MONGODB_DB_PARAMS=${MONGODB_DB_PARAMS}
      - JWT_SECRET=${JWT_SECRET}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_APP_SECRET=${PAYPAL_APP_SECRET}
      - PAYPAL_API_URL=${PAYPAL_API_URL}

    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
