name: Dockerize

on:
  workflow_call:
    inputs:
      source-code-path:
        description: 'Source of the Docker image (webapi or webapp)'
        required: true
        type: string
      docker-image:
        description: 'Docker image name'
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        description: 'Docker Hub username'
        required: true
      DOCKER_PASSWORD:
        description: 'Docker Hub password'
        required: true

jobs:
  dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ inputs.docker-image }} -f ${{inputs.source-code-path}}/Dockerfile ${{inputs.source-code-path}}
          docker push ${{ inputs.docker-image }}
