name: Web App Dev CI & CD

on:
  push:
    branches:
      - dev
    paths:
      - 'src/webapp/**'
      - '.github/workflows/webapp-ci-cd-dev.yml'
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      source-code-path: src/webapp

  dependency-check:
    needs: lint
    uses: ./.github/workflows/dependency-check.yml
    with:
      source-code-path: src/webapp

  security:
    needs: dependency-check
    uses: ./.github/workflows/security.yml
    with:
      source-code-path: src/webapp

  test:
    needs: security
    uses: ./.github/workflows/test.yml
    with:
      source-code-path: src/webapp

  code-coverage:
    needs: test
    uses: ./.github/workflows/code-coverage.yml
    with:
      source-code-path: src/webapp

  dockerize:
    needs: code-coverage
    uses: ./.github/workflows/dockerize.yml
    with:
      source-code-path: src/webapp
      docker-image: prasadhonrao/sportiverse-webapp:dev
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: dockerize
    uses: ./.github/workflows/azure-app-service-deploy.yml
    with:
      docker-image: prasadhonrao/sportiverse-webapp:dev
      azure-app-service-name: sportiverse-webapp
      deployment-slot: dev
    secrets:
      AZURE_SERVICE_PRINCIPAL: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

  gmail-notify:
    uses: ./.github/workflows/gmail-notify.yml
    needs: deploy
    if: always() # Always run this job even if the previous jobs fail
    with:
      status: ${{ needs.deploy.result }}
      repository: ${{ github.repository }}
      branch: ${{ github.ref }}
      commit: ${{ github.sha }}
      actor: ${{ github.actor }}
      workflow: ${{ github.workflow }}
      job: ${{ github.job }}
      run_id: ${{ github.run_id }}
      run_number: ${{ github.run_number }}
    secrets:
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      NOTIFY_EMAIL: ${{ secrets.NOTIFY_EMAIL }}
