name: WebAPI Prod CI & CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE: prasadhonrao/sportiverse-webapi
  AZURE_WEBAPP_NAME: sportiverse-webapi

jobs:
  deploy:
    uses: ./.github/workflows/reusable-webapi-ci-cd.yml
    with:
      docker-tag: latest
      deployment-slot: production
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AZURE_SERVICE_PRINCIPAL: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

  gmail-notify:
    uses: ./.github/workflows/reusable-gmail-notify.yml
    needs: deploy
    if: always() # Always run this job even if the previous jobs fail
    with:
      status: ${{ needs.deploy.result }}
      repository: ${{ github.repository }}
      branch: ${{ github.ref }}
      commit: ${{ github.sha }}
      actor: ${{ github.actor }}
      workflow: ${{ github.workflow }}
      job: ${{ github.job }}
      run_id: ${{ github.run_id }}
      run_number: ${{ github.run_number }}
