name: Web App Prod CI & CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/azure-app-service-deploy.yml
    with:
      docker-image: prasadhonrao/sportiverse-webapp
      azure-app-service-name: sportiverse-webapp
      deployment-slot: production
    secrets:
      AZURE_SERVICE_PRINCIPAL: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

  gmail-notify:
    uses: ./.github/workflows/gmail-notify.yml
    needs: deploy
    if: always() # Always run this job even if the previous jobs fail
    with:
      status: ${{ needs.deploy.result }}
      repository: ${{ github.repository }}
      branch: ${{ github.ref }}
      commit: ${{ github.sha }}
      actor: ${{ github.actor }}
      workflow: ${{ github.workflow }}
      job: ${{ github.job }}
      run_id: ${{ github.run_id }}
      run_number: ${{ github.run_number }}
    secrets:
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      NOTIFY_EMAIL: ${{ secrets.NOTIFY_EMAIL }}
