name: WebAPI Azure Deploy

on:
  push:
    branches:
      - dev
    paths:
      - 'src/webapi/**'
      - '.github/workflows/webapi-azure-deploy.yml'
  workflow_dispatch:

env:
  DOCKER_IMAGE: prasadhonrao/sportiverse-webapi:dev
  AZURE_WEBAPP_NAME: sportiverse-webapi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: '${{ env.DOCKER_IMAGE }}'
          slot-name: dev
