name: WebAPI Dev CI & CD

on:
  push:
    branches:
      - dev
    paths:
      - 'src/webapi/**'
      - '.github/workflows/webapi-ci-cd-dev.yml'
  workflow_dispatch:

env:
  DOCKER_IMAGE: prasadhonrao/sportiverse-webapi
  DOCKER_TAG: dev
  AZURE_APP_SERVICE_NAME: sportiverse-webapi
  AZURE_APP_SERVICE_DEPLOYMENT_SLOT: dev
  SOURCE_CODE_PATH: src/webapi

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      source-code-path: ${{ env.SOURCE_CODE_PATH }}

  dependency-check:
    needs: lint
    uses: ./.github/workflows/dependency-check.yml
    with:
      source-code-path: ${{ env.SOURCE_CODE_PATH }}

  security:
    needs: dependency-check
    uses: ./.github/workflows/security.yml
    with:
      source-code-path: ${{ env.SOURCE_CODE_PATH }}

  test:
    needs: security
    uses: ./.github/workflows/test.yml
    with:
      source-code-path: src/webapi

  code-coverage:
    needs: test
    uses: ./.github/workflows/code-coverage.yml
    with:
      source-code-path: src/webapi

  dockerize:
    needs: code-coverage
    uses: ./.github/workflows/dockerize.yml
    with:
      source-code-path: ${{ env.SOURCE_CODE_PATH }}
      docker-image: ${{ env.DOCKER_IMAGE }}
      docker-tag: ${{ env.DOCKER_TAG }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: dockerize
    uses: ./.github/workflows/azure-app-service-deploy.yml
    with:
      docker-image: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
      deployment-slot: ${{ env.AZURE_APP_SERVICE_DEPLOYMENT_SLOT }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AZURE_SERVICE_PRINCIPAL: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

  gmail-notify:
    uses: ./.github/workflows/gmail-notify.yml
    needs: deploy
    if: always() # Always run this job even if the previous jobs fail
    with:
      status: ${{ needs.deploy.result }}
      repository: ${{ github.repository }}
      branch: ${{ github.ref }}
      commit: ${{ github.sha }}
      actor: ${{ github.actor }}
      workflow: ${{ github.workflow }}
      job: ${{ github.job }}
      run_id: ${{ github.run_id }}
      run_number: ${{ github.run_number }}
    secrets:
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      NOTIFY_EMAIL: ${{ secrets.NOTIFY_EMAIL }}
